from operations import *
from read import *

def buying(neededInfo, current_date, anotherOne, total, nameOfBuyer, date_string, addressOfBuyer, contactOfBuyer):
    shippingCost = 1500
    print("\n")
    print("\t\t\t\t---------------------------")
    print("\t\t\t\t   Korone's manufacture")
    print("\t\t\t\t---------------------------")
    print("\t\t\t\t         Your bill ")
    print("Date: " + str(date_string))
    print("Customer Name: " + str(nameOfBuyer)) 
    print("Customer Phone Number: " + str(contactOfBuyer))
    print("Customer Address: " + str(addressOfBuyer))
    print("------------------------------------------------------------------------------------------")
    print("\t\t\t\t      Laptop Details: ")
    print("------------------------------------------------------------------------------------------")
    print("Item name \t Company Name \t\t  Total Quantity \t Laptop Price \t    Total")
    print("------------------------------------------------------------------------------------------")
    print("\n")
    for i in neededInfo:
        print(i[0], "    ", i[1], "\t\t      ", i[2], "\t\t  ", "$" , i[3], "\t  " , "$" , i[4])
    print("\n")
    print("------------------------------------------------------------------------------------------")
    print("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tGrand Total: " + "$" + str(total))
    print("Your Shopping Cost is: $", shippingCost)
    sp = total + 1500
    print("Grand Total(With Shipping cost)", "$ ", sp)
    print("\n")
    print("\t\t    ------------------------------------------------")
    print("\t\t      THANK YOU FOR CHOOSING Korone's Manufacture!")
    print("\t\t    ------------------------------------------------")
    print("\n")

    return sp

def bill_txt(buylaptop, neededInfo, date_string, anotherOne, nameOfBuyer, contactOfBuyer, addressOfBuyer, Stocks, idNumber, selecting, terminal_bill, total):
    sp = total + 500
    shippingCost = 1500
    file = open(str(nameOfBuyer) + str(date_string) + ".txt", "w")
    file.write("\t\t\t\t\t\t\t\t---------------------------")
    file.write("\n")
    file.write("\t\t\t\t\t\t\t\t   Korone's manufacture")
    file.write("\n")
    file.write("\t\t\t\t\t\t\t\t---------------------------")
    file.write("\n")
    file.write("\t\t\t\t\t\t\t\t        Your bill ")
    file.write("\n")
    file.write("Date: " + str(date_string))
    file.write("\n")
    file.write("Customer Name: " + str(nameOfBuyer))
    file.write("\n")
    file.write("Customer Phone Number: " + str(contactOfBuyer))
    file.write("\n")
    file.write("Customer Address: " + str(addressOfBuyer))
    file.write("\n")
    file.write("----------------------------------------------------------------------------------------------------------------")
    file.write("\n")
    file.write("\t\t\t\t\t\t\t\t      Laptop Details: ")
    file.write("\n")
    file.write("----------------------------------------------------------------------------------------------------------------")
    file.write("\n")
    file.write(
        "Item name \t\t\t Company Name \t\t\t Total Quantity \t\t Laptop Price \t\t Total")
    file.write("\n")
    file.write("----------------------------------------------------------------------------------------------------------------")
    file.write("\n\n")
    for i in neededInfo:
        file.write(str(i[0]) + "\t\t" + str(i[1]) + "\t\t\t\t\t   " + str(i[2]) + "\t\t\t\t" + "$" + str(i[3]) + "\t\t" + "$" + str(i[4]) + "\n")
    file.write("\n")
    file.write("----------------------------------------------------------------------------------------------------------------")
    file.write("\n")
    file.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t Grand Total: " + "$" + str(total))
    file.write("\n")
    file.write("Your Shipping Cost is: $" + str(shippingCost))
    file.write("\n")
    for i in neededInfo:
        file.write("Grand Total(With Shipping cost): $" + str(sp))
    file.write("\n\n")
    file.write("\t\t\t\t\t\t    ------------------------------------------------")
    file.write("\n")
    file.write("\t\t\t\t\t\t      THANK YOU FOR CHOOSING Korone's Manufacture!")
    file.write("\n")
    file.write("\t\t\t\t\t\t    ------------------------------------------------")
    file.write("\n")

def restockbill(Stocks, idNumber, qnty, qnty_restock, restock, total, vat, nameOfBuyer, date_string):
    laptopPrice = Stocks[idNumber][2].replace("$", "")
    print("\n")
    print("\t\t\t\t---------------------------")
    print("\t\t\t\t   Korone's manufacture")
    print("\t\t\t\t---------------------------")
    print("\t\t\t\t         Your bill ")
    print("Date:" + str(date_string))
    print("Customer Name: " + str(nameOfBuyer))
    print("-------------------------------------------------------------------------------")
    print("\t\t\t\t      Laptop Details: ")
    print("-------------------------------------------------------------------------------")
    print("Item name \t Company Name \t\t  Total Quantity \t Laptop Price")
    print("-------------------------------------------------------------------------------")
    print("\n")
    for i in restock:
        print(i[0], "    ", i[1], "\t\t      ", i[2], "\t\t  ", "$" , i[3])
    print("\n")
    print("-------------------------------------------------------------------------------")
    print(f"The Grand Total is: $ {int(total) * int(laptopPrice)}") 

    print("Price with 13% Vat: $", vat)    
    print("\n")
    print("\t\t    ------------------------------------------------")
    print("\t\t      THANK YOU FOR CHOOSING Korone's Manufacture!")
    print("\t\t    ------------------------------------------------")
    print("\n")

def restockbill_save(Stocks, idNumber, qnty, qnty_restock, restock, total, vat, nameOfBuyer, date_string):
    laptopPrice = Stocks[idNumber][2].replace("$", "")
    file = open(f"Restock_{nameOfBuyer}{date_string}.txt","w")
    file.write("\n")
    file.write("\t\t\t\t---------------------------")
    file.write("\n")
    file.write("\t\t\t\t   Korone's manufacture")
    file.write("\n")
    file.write("\t\t\t\t---------------------------")
    file.write("\n")
    file.write("\t\t\t\t         Your bill ")
    file.write("\n")
    file.write("Date:" + str(date_string))
    file.write("\n")
    file.write("Customer Name: " + str(nameOfBuyer))
    file.write("\n")
    file.write("------------------------------------------------------------------------------------------")
    file.write("\n")
    file.write("\t\t\t\t      Laptop Details: ")
    file.write("\n")
    file.write("------------------------------------------------------------------------------------------")
    file.write("\n")
    file.write("Item name \t\t Company Name \t\t  Total Quantity \t\t Laptop Price")
    file.write("\n")
    file.write("------------------------------------------------------------------------------------------")
    file.write("\n")
    file.write("\n")
    for i in restock:
        file.write(str(i[0])+ "         "+ str(i[1])+ "\t\t\t  "+ str(i[2])+ "\t\t         "+ "$" +str(i[3]) + "\n")
    file.write("\n")
    file.write("\n")
    file.write("------------------------------------------------------------------------------------------")
    file.write("\n")
    file.write(f"The Grand Total is: ${int(total) * int(laptopPrice)}") 
    file.write("\n")
    file.write("Price with 13% Vat: $"+ str(vat))    
    file.write("\n")
    file.write("\n")
    file.write("\t\t    ------------------------------------------------")
    file.write("\n")
    file.write("\t\t      THANK YOU FOR CHOOSING Korone's Manufacture!")
    file.write("\n")
    file.write("\t\t    ------------------------------------------------")
    file.write("\n")